---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:
    - name: Make continous deployment to server
      git:
        repo: 'https://github.com/samsonmuoki/zusha_web_app.git'
        dest: project/
        force: yes
        # owner: sam
    
    - name: Installing requirements
      pip:
        requirements: /home/sam/project/requirements/requirements_main.txt
        virtualenv: /home/sam/project/venv
        virtualenv_python: python3.6

    - name: Activate venv and make migrations
      shell: |
        . /home/sam/project/env.sh
        . /home/sam/project/venv/bin/activate
        pip3 install -r /home/sam/project/requirements/requirements_main.txt
        python3 /home/sam/project/zusha/manage.py makemigrations --noinput
        python3 /home/sam/project/zusha/manage.py migrate --noinput
    
    - name: Recursively change ownership of static directory
      file:
        path: /home/sam/project/static
        state: directory
        recurse: yes
        owner: sam
        mode: 0777
    
    - name: Collect static
      shell: |
        . /home/sam/project/env.sh
        . /home/sam/project/venv/bin/activate
        python3 /home/sam/project/zusha/manage.py collectstatic --noinput

    - name: Start gunicorn
      shell: |
        . /home/sam/project/env.sh
        . /home/sam/project/venv/bin/activate
        cd /home/sam/project/zusha
        gunicorn --daemon --workers 3 --bind unix:/home/sam/project/zusha/zusha_app.sock zusha_app.wsgi
          

