---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:

          - name: Add universe repository for bionic
            apt_repository: 
              repo: deb http://archive.ubuntu.com/ubuntu bionic universe
              state: present
            when: ansible_distribution_release == 'bionic'

          - name: Install base packages
            apt: 
              name: "{{ packages }}"
            vars:
              packages:
                - locales
                - build-essential
                - htop
                - git
                - python3-apt
                - python3-pip
                - python-psycopg2
                - supervisor
                # - redis-server
                - rabbitmq-server
                - postgresql
                - libpq-dev
                - ufw
                - psmisc
                - curl
          
          - name: Ensure PostgreSQL service is running
            service:
              name: postgresql
              state: started
              enabled: yes

          - name: install setfacl support to enable ansible create temporary files
            become: yes
            apt: pkg=acl
          
          - name: Create database
            become: yes
            become_user: postgres
            become_method: sudo
            postgresql_db:
              name: zusha
              state: present
            

          - name: Ensure user has access to db
            become: yes
            become_user: postgres
            postgresql_user:
              db: zusha
              name: admin
              password: admin
              priv: ALL
              state: present
            
          - name: Create project directory
            file:
              state: directory
              path: project
          
          - name: Pull project from github
            git:
              repo: 'https://github.com/samsonmuoki/zusha_web_app.git'
              dest: project/

          - name: Copy env.sh to server
            copy:
              src: /home/sam/Desktop/4th_Year_Project/zusha_web_app/env.sh
              dest: /home/sam/project/
              mode: 0766
          
          - name: Stop supervisor
            service:
              name: supervisor
              state: stopped
          
          - name: Install virtualenv
            pip: 
              name: virtualenv
              executable: pip3
            become: yes
            become_user: root              
          
          - name: Create virtualenv
            command: /usr/local/bin/virtualenv project/venv
            
          - name: Installing requirements
            pip:
              requirements: /home/sam/project/requirements/requirements_main.txt
              virtualenv: /home/sam/project/venv
              virtualenv_python: python3.6

          - name: Activate venv and make migrations
            shell: |
              . /home/sam/project/env.sh
              . /home/sam/project/venv/bin/activate
              python3 /home/sam/project/zusha/manage.py migrate
          
          # - name: Collect static
          #   shell: |
          #     . /home/sam/project/env.sh
          #     . /home/sam/project/venv/bin/activate
          #     python3 /home/sam/project/zusha/manage.py collectstatic


          - name: Recursively change ownership of zusha directory
            file:
              path: /home/sam/project/zusha
              state: directory
              recurse: yes
              owner: sam