---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:

          - name: add universe repository for bionic
            apt_repository: 
              repo: deb http://archive.ubuntu.com/ubuntu bionic universe
              state: present
            when: ansible_distribution_release == 'bionic'
  
          - name: Install base packages
            apt: 
              name: "{{ packages }}"
            vars:
              packages:
                - locales
                - build-essential
                - htop
                - git
                - python3-apt
                - python3-pip
                # - redis-server
                - supervisor
                        
          # - name: Upgrade pip
          #   pip: name=pip state=latest
            
          - name: Create directory muoki
            file:
              state: directory
              path: muoki
          
          - name: Pull project from github
            git:
              repo: 'https://github.com/samsonmuoki/Django-PollsApp.git'
              dest: muoki/

          # - name: copy db to server
          #   copy:
          #     src: /home/sam/Desktop/Django_Tutorial/Django-PollsApp/pollsapp/db.sqlite3
          #     dest: /home/sam/muoki/pollsapp/
          #     mode: 0777
          
          - name: Install setuptools
            pip:
              name: setuptools
              executable: pip3
          

          # - name: install virtualenv
          #   pip: 
          #     name: virtualenv
          #     executable: pip3
          #   become: yes
          #   become_user: root              
          
          # - name: create virtualenv
          #   command: /usr/local/bin/virtualenv muoki/venv
            
          - name: installing requirements
            # command: pip3 install -r /home/sam/muoki/pollsapp/requirements.txt
            pip:
              requirements: /home/sam/muoki/pollsapp/requirements.txt
              # virtualenv: /home/sam/muoki/venv
              # virtualenv_python: python3.6

          - name: activate venv and make migrations
            shell: |
              # . /home/sam/muoki/venv/bin/activate
              python3 /home/sam/muoki/pollsapp/manage.py migrate

          - name: Recursively change ownership of pollsapp directory
            file:
              path: /home/sam/muoki/pollsapp
              state: directory
              recurse: yes
              owner: sam