# Generated by Django 3.0.6 on 2020-06-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200529_2035'),
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SaccoAdmin',
            new_name='SaccoUser',
        ),
    ]
