# Generated by Django 3.0.3 on 2020-02-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=200)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Sacco')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_id', models.CharField(max_length=200)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Sacco')),
            ],
        ),
    ]
