# Generated by Django 3.0.3 on 2020-02-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_id',
        ),
    ]
