# Generated by Django 3.0.3 on 2020-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_driver_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.IntegerField(default=0),
        ),
    ]
