# Generated by Django 3.0.3 on 2020-02-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_driver_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(max_length=200),
        ),
    ]
