# Generated by Django 3.0.3 on 2020-02-17 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200217_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sacco',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2020, 2, 17, 9, 9, 38, 648231, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sacco',
            name='sacco_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=200),
        ),
    ]
