# Generated by Django 3.0.6 on 2020-06-13 07:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=8, unique=True)),
                ('surname', models.CharField(max_length=10)),
                ('other_names', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB', 'AB+'), ('AB', 'AB-')], max_length=10)),
                ('license_number', models.CharField(max_length=10)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('county_of_residence', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Kwale', 'Kwale'), ('Kilifi', 'Kilifi'), ('Tana River', 'Tana River'), ('Lamu', 'Lamu'), ('Taita-Taveta', 'Taita/Taveta'), ('Garissa', 'Garissa'), ('Wajir', 'Wajir'), ('Mandera', 'Mandera'), ('Marsabit', 'Marsabit'), ('Isiolo', 'Isiolo'), ('Meru', 'Meru'), ('Tharaka-Nithi', 'Tharaka-Nithi'), ('Embu', 'Embu'), ('Kitui', 'Kitui'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Kirinyaga', 'Kirinyaga'), ('Muranga', "Murang'a"), ('Kiambu', 'Kiambu'), ('Turkana', 'Turkana'), ('West Pokot', 'West Pokot'), ('Samburu', 'Samburu'), ('Trans Nzoia', 'Trans Nzoia'), ('Uasin Gishu', 'Uasin Gishu'), ('Elgeyo-Marakwet', 'Elgeyo/Marakwet'), ('Nandi', 'Nandi'), ('Baringo', 'Baringo'), ('Laikipia', 'Laikipia'), ('Nakuru', 'Nakuru'), ('Narok', 'Narok'), ('Kajiado', 'Kajiado'), ('Kericho', 'Kericho'), ('Bomet', 'Bomet'), ('Kakamega', 'Kakamega'), ('Vihiga', 'Vihiga'), ('Bungoma', 'Bungoma'), ('Busia', 'Busia'), ('Siaya', 'Siaya'), ('Kisumu', 'Kisumu'), ('Homa Bay', 'Homa Bay'), ('Migori', 'Migori'), ('Kisii', 'Kisii'), ('Nyamira', 'Nyamira'), ('Nairobi', 'Nairobi')], max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('license_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sacco_name', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_inspection_date', models.DateField()),
                ('license_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=7, unique=True)),
                ('name_of_owner', models.CharField(max_length=50)),
                ('owner_national_id', models.CharField(max_length=10)),
                ('year_of_manufacture', models.IntegerField()),
                ('engine_capacity', models.IntegerField()),
                ('vehicle_body_type', models.CharField(choices=[('van', 'Van'), ('minivan', 'Minivan'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('luxury', 'Luxury'), ('muv', 'Multi-Utility Vehicle'), ('notchback', 'Notchback'), ('sedan', 'Sedan'), ('sportscar', 'Sports Car'), ('suv', 'Sports Utility Vehicle'), ('wagon', 'Wagon'), ('supercars', 'Super Cars'), ('truck', 'Truck')], max_length=20)),
                ('color_of_vehicle', models.CharField(max_length=20)),
                ('registered_logbook_number', models.CharField(max_length=50)),
                ('registered_engine_number', models.CharField(max_length=50)),
                ('registered_chasis_number', models.CharField(max_length=50)),
                ('last_inspection_date', models.DateField()),
                ('inspection_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='SaccoVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Sacco')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registrations.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SaccoDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registrations.RegisteredDriver')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Sacco')),
            ],
        ),
    ]
