# Generated by Django 3.0.6 on 2020-05-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('sacco_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('license_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=200)),
                ('license_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Sacco')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=200)),
                ('driver_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('license_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Sacco')),
            ],
        ),
    ]
