# Generated by Django 3.0.6 on 2020-06-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saccodriver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='saccodriver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='saccodriver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='saccodriver',
            name='phone_number',
        ),
    ]
