# Generated by Django 3.0.6 on 2020-05-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='sacco',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sacco',
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='blank', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='blank', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='SaccoVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Sacco')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='SaccoDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Driver')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registrations.Sacco')),
            ],
        ),
    ]
