# Generated by Django 3.0.6 on 2020-06-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20200613_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_body_type',
            field=models.CharField(choices=[('van', 'Van'), ('minivan', 'Minivan'), ('bus', 'Bus'), ('minibus', 'Minibus'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('luxury', 'Luxury'), ('muv', 'Multi-Utility Vehicle'), ('notchback', 'Notchback'), ('sedan', 'Sedan'), ('sportscar', 'Sports Car'), ('suv', 'Sports Utility Vehicle'), ('wagon', 'Wagon'), ('supercars', 'Super Cars'), ('truck', 'Truck')], max_length=20),
        ),
    ]
