# Generated by Django 3.0.6 on 2020-05-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200520_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacco',
            name='sacco_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
