# Generated by Django 3.0.6 on 2020-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200621_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saccodriver',
            name='last_status_update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
