# Generated by Django 3.0.6 on 2020-06-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200529_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=8, unique=True)),
                ('surname', models.CharField(max_length=10)),
                ('other_names', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB', 'AB+'), ('AB', 'AB-')], max_length=10)),
                ('license_number', models.CharField(max_length=10)),
                ('date_of_issue', models.DateField()),
                ('date_of_expiry', models.DateField()),
                ('county_of_residence', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Nairobi', 'Nairobi'), ('Machakos', 'Machakos')], max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('license_status', models.CharField(choices=[('approved', 'Approved to operate'), ('expired', 'License not renewed'), ('blacklisted', 'Not approved to operate')], default='approved', max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='sacco',
            name='address',
            field=models.TextField(default='MIAMI', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color_of_vehicle',
            field=models.CharField(default='BLUE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name_of_owner',
            field=models.CharField(default='mr money', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_national_id',
            field=models.CharField(default=12345678, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_chasis_number',
            field=models.CharField(default='chasis_001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_engine_number',
            field=models.CharField(default='engine_002', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registered_logbook_number',
            field=models.CharField(default='logbook_001', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_body_type',
            field=models.CharField(choices=[('van', 'Van'), ('minivan', 'Minivan'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('crossover', 'Crossover'), ('Hatchback', 'Hatchback'), ('luxury', 'Luxury'), ('muv', 'Multi-Utility Vehicle'), ('notchback', 'Notchback'), ('sedan', 'Sedan'), ('sportscar', 'Sports Car'), ('suv', 'Sports Utility Vehicle'), ('wagon', 'Wagon'), ('supercars', 'Super Cars'), ('truck', 'Truck')], default='truck', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saccodriver',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registrations.RegisteredDriver'),
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
