# Generated by Django 3.0.6 on 2020-07-10 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200710_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='saccovehicle',
            name='date_registered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
