# Generated by Django 3.0.6 on 2020-06-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20200611_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.IntegerField(max_length=4),
        ),
    ]
