---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:            
          
          - name: start gunicorn
            shell: |
              . /home/sam/muoki/venv/bin/activate
              cd /home/sam/muoki/pollsapp
              gunicorn --daemon --workers 3 --bind unix:/home/sam/muoki/pollsapp/pollsapp.sock pollsapp.wsgi
            
          

