all:
        hosts:
                test:
                        # ansible_user: sam
                        ansible_user: ubuntu
                        ansible_host: zusha.duckdns.org
                        