---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: yes
    - name: start nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: copy the nginx config file and restart nginx
      copy:
        src: /home/sam/Desktop/4th Year Project/configuration_files/nginx/zusha_app
        dest: /etc/nginx/sites-available
      become: yes
    - name: create symlink
      file:
        src: /etc/nginx/sites-available/zusha_app
        dest: /etc/nginx/sites-enabled/default
        state: link
      become: yes
    
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes