# Generated by Django 3.0.6 on 2020-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('sacco', models.CharField(max_length=10)),
                ('speed', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=20)),
            ],
        ),
    ]
