# Generated by Django 3.0.6 on 2020-05-20 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 10, 38, 23, 555703, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='driver',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='regno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='sacco',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
