# Generated by Django 3.0.6 on 2020-06-15 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20200615_0714'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydriverreport',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registrations.SaccoDriver'),
        ),
        migrations.AlterField(
            model_name='dailyvehiclereport',
            name='sacco_action_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
