# Generated by Django 3.0.6 on 2020-06-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200615_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydriverreport',
            name='regno',
            field=models.CharField(default='kac', max_length=10),
            preserve_default=False,
        ),
    ]
