# Generated by Django 3.0.6 on 2020-05-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200520_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ntsa_resolution',
            field=models.CharField(choices=[('pending', 'No action was taken'), ('in_progress', 'Currently being resolved'), ('resolved', 'Corrective Action was taken')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='sacco_resolution',
            field=models.CharField(choices=[('pending', 'No action was taken'), ('in_progress', 'Currently being resolved'), ('resolved', 'Corrective Action was taken')], default='pending', max_length=20),
        ),
    ]
