# Generated by Django 3.0.6 on 2020-05-20 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200520_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 20, 20, 4, 55, 511263, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
