# Generated by Django 3.0.6 on 2020-05-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200529_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackDriverReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrackSaccoReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sacco', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
