# Generated by Django 3.0.6 on 2020-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_trackdriverreports_tracksaccoreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ntsa_resolution',
        ),
        migrations.RemoveField(
            model_name='report',
            name='sacco_resolution',
        ),
        migrations.AlterField(
            model_name='trackvehiclereports',
            name='ntsa_action',
            field=models.CharField(choices=[('Pending', 'No action was taken'), ('In Progress', 'Currently being resolved'), ('Resolved', 'Corrective Action was taken')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackvehiclereports',
            name='sacco_action',
            field=models.CharField(choices=[('Pending', 'No action was taken'), ('In Progress', 'Currently being resolved'), ('Resolved', 'Corrective Action was taken')], default='Pending', max_length=20),
        ),
    ]
