# Generated by Django 3.0.6 on 2020-06-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_trackdriverreports_sacco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackvehiclereports',
            name='ntsa_action',
            field=models.CharField(choices=[('Pending', 'No action was taken'), ('In-Progress', 'Currently being resolved'), ('Resolved', 'Corrective Action was taken')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trackvehiclereports',
            name='sacco_action',
            field=models.CharField(choices=[('Pending', 'No action was taken'), ('In-Progress', 'Currently being resolved'), ('Resolved', 'Corrective Action was taken')], default='Pending', max_length=20),
        ),
    ]
