# Generated by Django 3.0.6 on 2020-06-11 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20200611_1927'),
        ('reports', '0011_auto_20200610_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVehicleReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10)),
                ('sacco', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('ntsa_action', models.CharField(choices=[('Pending', 'No action was taken'), ('In-Progress', 'Currently being resolved'), ('Resolved', 'Corrective Action was taken')], default='Pending', max_length=20)),
                ('ntsa_action_description', models.TextField(max_length=500, null=True)),
                ('sacco_action', models.CharField(choices=[('Pending', 'No action was taken'), ('In-Progress', 'Currently being resolved'), ('Resolved', 'Corrective Action was taken')], default='Pending', max_length=20)),
                ('sacco_action_description', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10, null=True)),
                ('sacco', models.CharField(max_length=20, null=True)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('location', models.CharField(max_length=100, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registrations.SaccoDriver')),
            ],
        ),
        migrations.RenameModel(
            old_name='TrackDriverReports',
            new_name='DailyDriverReport',
        ),
        migrations.RenameModel(
            old_name='TrackSaccoReports',
            new_name='DailySaccoReport',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='TrackVehicleReports',
        ),
    ]
